# Generated by Django 5.1.7 on 2025-03-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=10)),
                ("message", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Esports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("duration", models.CharField(max_length=50)),
                ("fee", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("team_size", models.CharField(max_length=10)),
                ("prize_pool", models.CharField(max_length=20)),
            ],
        ),
    ]
